name: TNTOnSand
version: '1.0'
main: am.FroshGames.tNTRun.TNTOnSand
api-version: '1.20'
commands:
  toggleTNT:
    description: Activa o desactiva la generación de TNT en arena.
    usage: /toggleTNT
